# Generated by Django 2.2 on 2019-04-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_business_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default='SA', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='nid',
            field=models.AutoField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
