# Generated by Django 2.2 on 2019-04-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_auto_20190412_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Aplication')),
                ('hboj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Host')),
            ],
        ),
    ]
