# Generated by Django 2.2 on 2019-04-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_aplication_hostapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostApp',
        ),
    ]
