# Generated by Django 2.2 on 2019-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_delete_hostapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='r',
            field=models.ManyToManyField(to='app02.Host'),
        ),
    ]
