# Generated by Django 2.2 on 2019-04-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.ImageField(choices=[(1, '超级用户'), (1, '普通用户'), (1, '游客')], default=1, upload_to=''),
        ),
    ]
